source 'https://rubygems.org'

puppet_version = ENV.key?('PUPPET_VERSION') ? "= #{ENV['PUPPET_VERSION']}" : ['>= 2.7']

gem 'rake',                   '~> 10.5.0'
gem 'puppet',                 puppet_version
gem 'puppet-lint'
gem 'puppetlabs_spec_helper', '>= 0.1.0'

