source 'https://rubygems.org'

puppet_version = ENV.key?('PUPPET_VERSION') ? "= #{ENV['PUPPET_VERSION']}" : ['>= 2.7']

gem 'puppet',                 puppet_version
gem 'puppetlabs_spec_helper', '>= 0.1.0'

