source 'https://rubygems.org'

puppet_version = ENV.key?('PUPPET_VERSION') ? "= #{ENV['PUPPET_VERSION']}" : ['>= 2.7']

gem 'puppet',                 puppet_version
gem 'puppet-lint'
gem 'metadata-json-lint'
gem 'puppetlabs_spec_helper', '>= 0.1.0'

if RUBY_VERSION >= '1.8.7' && RUBY_VERSION < '1.9'
  gem 'rake',  '~> 10.5.0'
  gem 'rspec', '~> 2.0'
end

if RUBY_VERSION < '2.0'
  gem 'json', '<= 1.8.3'
end
